### ISSUE TITLE
New API Doc - Site Parity Issue :  Missing Status code 

### ISSUE THREAD

**Issue by rshera01** [opsramp/openapi-specs#10]
- All of the DELETE API's do not have the status code mentioned. We have found that the status code ( HTTP status codes)  are not uniformly mentioned across all API. There needs consistency to mention status codes across all API in the product features.

**Comment by rshera01** [comment]
@geneopsramp ,
Since we have the Status code references xxxx/api/about/status-codes/  this should serve the purpose for the release.
closing the issue

**Comment by geneopsramp** [comment]
Actually, the generic status code reference in About is insufficient. It's adequate for general purposes but somewhat useless because everyone already knows https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html.
The status codes are still needed for each endpoint. Their intent within the endpoint documentation is to specifically describe why, in terms of OpsRamp-specific functionality, that status code was received. They also serve the purpose of reminding developers creating the endpoint code to consider all of the error conditions that might be generated by the endpoint and map the error to a status code (although, good luck with that). It's OK to close this issue because it's just one of a number of API doc usability issues and will be covered eventually in the grand scheme of things.

**Comment by rshera01** [comment]
Yes Agreed, that why we need to push this ask next  update of API documentation.
